# Generated by Django 5.2.4 on 2025-07-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_redo_all_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
    ]
