# Generated by Django 5.2.4 on 2025-07-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_Company_Role_Employee_Shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='temp_unassigned_default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.OneToOneField(limit_choices_to={'is_manager': True}, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='api.employee'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.company')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='api.position'),
        ),
        migrations.AddField(
            model_name='shift',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.position'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
