# Generated by Django 5.2.4 on 2025-07-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_is_manager_field'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='employee',
        #     name='is_manager',
        # ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.OneToOneField(limit_choices_to={'is_manager': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='api.employee'),
        ),
    ]
